# Generated by Django 5.0.7 on 2024-07-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_upload',
            name='file_category',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='new_upload',
            name='file_source',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='new_upload',
            name='file_ver',
            field=models.TextField(default=None),
        ),
    ]
