# Generated by Django 5.0.7 on 2024-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0002_new_upload_file_category_new_upload_file_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_upload',
            name='file_des',
        ),
        migrations.AddField(
            model_name='new_upload',
            name='file_required_size',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='new_upload',
            name='file_size',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='new_upload',
            name='file_category',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='new_upload',
            name='file_link',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='new_upload',
            name='file_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='new_upload',
            name='file_source',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='new_upload',
            name='file_ver',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
