# Generated by Django 5.0.7 on 2024-08-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0003_remove_new_upload_file_des_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_upload',
            old_name='file_name',
            new_name='name',
        ),
    ]
