# Generated by Django 5.0.7 on 2024-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0005_rename_name_new_upload_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=354)),
                ('subject', models.TextField()),
            ],
        ),
    ]
