# Generated by Django 5.0.7 on 2024-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0006_contact_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form_data',
            name='email',
            field=models.EmailField(max_length=354, null=None),
        ),
        migrations.AlterField(
            model_name='contact_form_data',
            name='name',
            field=models.CharField(max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='contact_form_data',
            name='subject',
            field=models.TextField(null=None),
        ),
    ]
