# Generated by Django 5.0.7 on 2024-08-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0007_alter_contact_form_data_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_form_data',
            old_name='subject',
            new_name='message',
        ),
    ]
