# Generated by Django 5.0.7 on 2024-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0008_rename_subject_contact_form_data_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poetry', models.TextField(default=None)),
                ('poet_name', models.CharField(max_length=100)),
            ],
        ),
    ]
