# Generated by Django 5.0.7 on 2024-08-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0009_poetry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='poetry',
            new_name='poetry_model',
        ),
    ]
