# Generated by Django 5.0.7 on 2024-08-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0011_android_apps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='android_apps',
            new_name='android_apps_model',
        ),
    ]
