# Generated by Django 5.0.7 on 2024-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfile', '0013_android_apps_model_app_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='android_apps_model',
            name='app_size',
            field=models.CharField(max_length=200),
        ),
    ]
